# Generated by Django 2.2.1 on 2019-05-07 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('term', models.CharField(max_length=50)),
                ('user', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('location', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
