# Generated by Django 2.2.1 on 2019-05-08 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectedTweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('term', models.CharField(max_length=50)),
                ('text', models.TextField()),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
