# Generated by Django 2.2.1 on 2019-05-09 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_selectedtweet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('term', models.CharField(max_length=50)),
                ('limit', models.IntegerField()),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
