# Generated by Django 2.2.1 on 2019-05-13 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0004_auto_20190513_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selectedtweet',
            name='ponctuation',
        ),
    ]
