# Generated by Django 2.2.1 on 2019-05-15 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0005_remove_selectedtweet_ponctuation'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrendingTopics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField()),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
